config/routes.rb
Rails.application.routes.draw do
  resources :levels
  resources :characteristics
  resources :products

  root 'products#index'

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  belongs_to :product
  has_many   :levels, dependent: :destroy
  accepts_nested_attributes_for :levels,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  validates :name,
            presence: true
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :characteristic
  validates :name,
          presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :characteristics, dependent: :destroy
  accepts_nested_attributes_for :characteristics,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  validates :name, :brand, 
            presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all? { |e|  }
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1
  # PATCH/PUT /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: 'Characteristic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_params
      params.require(:characteristic).permit(:name, :product_id, levels_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :characteristic_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    # @product.characteristics.build  
    # characteristic = @product.characteristics.build do |c|
    #   c.levels.build
    # end

    4.times do
      characteristic = @product.characteristics.build
      2.times {characteristic.levels.build}
      end
  end

  # GET /products/1/edit
  def edit  
    # characteristic = @product.characteristics.build do |c|
    #   c.levels.build
    # end
    @product.characteristics.build
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :brand, :description, characteristics_attributes: [:id, :name, :_destroy, levels_attributes: [:id, :name, :_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/characteristics/_form.html.erb
<%= form_for(@characteristic) do |f| %>
  <% if @characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
      <% @characteristic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing Characteristic</h1>

<%= render 'form' %>

<%= link_to 'Show', @characteristic %> |
<%= link_to 'Back', characteristics_path %>

app/views/characteristics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characteristics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characteristics.each do |characteristic| %>
      <tr>
        <td><%= characteristic.name %></td>
        <td><%= characteristic.product %></td>
        <td><%= link_to 'Show', characteristic %></td>
        <td><%= link_to 'Edit', edit_characteristic_path(characteristic) %></td>
        <td><%= link_to 'Destroy', characteristic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Characteristic', new_characteristic_path %>

app/views/characteristics/new.html.erb
<h1>New Characteristic</h1>

<%= render 'form' %>

<%= link_to 'Back', characteristics_path %>

app/views/characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @characteristic.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @characteristic.product %>
</p>

<%= link_to 'Edit', edit_characteristic_path(@characteristic) %> |
<%= link_to 'Back', characteristics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conjoint</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :characteristic_id %><br>
    <%= f.text_field :characteristic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Characteristic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.characteristic %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Characteristic:</strong>
  <%= @level.characteristic %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


  <%= f.fields_for :characteristics do |c| %>
    <fieldset>
      <%= c.label :name, "Caracteristica" %>
      <%= c.text_field :name %>
      <%= c.check_box :_destroy %>
      <%= c.label :_destroy, "Descartar" %>

      <%= c.fields_for :levels do |l| %>
        <fieldset>
          <%= l.label :name, "Nivel" %>
          <%= l.text_field :name %>
          <%= l.hidden_field :_destroy %>
          <%= link_to "Eliminar", '#', class: "remove_fields" %>
        </fieldset>
      <% end %>
    </fieldset>
  <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Producto</h1>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<h2>Atributos</h2>

<% if @product.characteristics.any? %>
  <ul>
    <% @product.characteristics.each do |c| %>
    <li>
      <%= c.name %> :
      <% c.levels.each do |l| %>
        <%= l.name %>,
      <% end %>
    </li>

    <% end %>
  </ul>
  <% else %>
  <p>Aun no se han creado atributos para este producto</p>
<% end %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>